import { ColorSchemeScript, MantineProvider } from '@mantine/core';

import '@mantine/core/styles.css';

// import './global.css';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>

      <body>
        <MantineProvider>{children}</MantineProvider>
      </body>
    </html>
  );
}
