import {
  ColorSchemeScript,
  MantineProvider,
  AppShell,
  Group,
  Burger,
  AppShellHeader,
  AppShellNavbar,
  AppShellMain,
  NavLink
} from '@mantine/core';
import Link from 'next/link';

import '@mantine/core/styles.css';
import {
  IconAddressBook,
  IconComponents,
  IconList,
  IconReceipt
} from '@tabler/icons-react';
import { ModalsProvider } from '@mantine/modals';

// import './global.css';

export const metadata = {
  title: 'Welcome to frontend',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>

      <body>
        <MantineProvider>
          <ModalsProvider>
            <AppShell
              header={{ height: 60 }}
              navbar={{
                width: 300,
                breakpoint: 'sm'
              }}
              padding="md"
            >
              <AppShellHeader>
                <Group h="100%" px="md">
                  <strong>Panaderia</strong>
                </Group>
              </AppShellHeader>

              <AppShellNavbar p="md">
                <NavLink
                  component={Link}
                  href="/clients"
                  label="Clients"
                  childrenOffset="28"
                  leftSection={<IconAddressBook size="1rem" stroke={1.25} />}
                >
                  <NavLink
                    component={Link}
                    href="/clients"
                    label="All Clients"
                  />
                  <NavLink
                    component={Link}
                    href="/clients/new"
                    label="New Client"
                  />
                </NavLink>

                <NavLink
                  component={Link}
                  href="/supplies"
                  label="Stock"
                  childrenOffset="28"
                  leftSection={<IconComponents size="1rem" stroke={1.25} />}
                >
                  <NavLink
                    component={Link}
                    href="/supplies"
                    label="All Supplies"
                  />
                  <NavLink
                    component={Link}
                    href="/supplies/new"
                    label="Add Supply"
                  />
                </NavLink>

                <NavLink
                  component={Link}
                  href="/recipes"
                  label="Recetas"
                  childrenOffset="28"
                  leftSection={<IconList size="1rem" stroke={1.25} />}
                >
                  <NavLink
                    component={Link}
                    href="/recipes"
                    label="All Recipes"
                  />
                  <NavLink
                    component={Link}
                    href="/recipes/new"
                    label="New Recipe"
                  />
                </NavLink>

                <NavLink
                  component={Link}
                  href="/orders"
                  label="Orders"
                  childrenOffset="28"
                  leftSection={<IconReceipt size="1rem" stroke={1.25} />}
                >
                  <NavLink component={Link} href="/orders" label="All Orders" />
                  <NavLink
                    component={Link}
                    href="/orders/new"
                    label="New Order"
                  />
                </NavLink>
              </AppShellNavbar>

              <AppShellMain>{children}</AppShellMain>
            </AppShell>
          </ModalsProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
